website/blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from website.extensions import db
from website.models import BlogPost
from website.blog_posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)


# Create a blog
@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(
            title=form.title.data, text=form.text.data, user_id=current_user.id
        )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for("core.index"))
    return render_template("create_post.html", form=form)


# View a blog
@blog_posts.route("/<int:blog_post_id>/view")
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template(
        "view_blog.html", title=blog_post.title, date=blog_post.date, post=blog_post
    )


# Update a blog
@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash("Blog Post Updated")
        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post.id))

    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template("create_post.html", title="Updating", form=form)


# Delete a blog
@blog_posts.route("/<int:blog_post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash("Blog Post Deleted")
    return redirect(url_for("core.index"))

website/core/views.py
from flask import Blueprint, render_template, request
from website.models import BlogPost

core = Blueprint("core", __name__)


@core.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(
        page=page, per_page=5
    )
    return render_template("index.html", blog_posts=blog_posts)


@core.route("/info")
def info():
    """General information about the website"""
    return render_template("about.html")

website/users/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from website.extensions import db
from website.models import BlogPost, User
from website.users.forms import LoginForm, RegistrationForm, UpdateUserForm
from website.users.picture_handler import add_profile_pic
from flask import abort

from sqlalchemy.exc import IntegrityError

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    """Register User"""
    form = RegistrationForm()
    if form.validate_on_submit():
        try:
            user = User(
                email=form.email.data,
                username=form.username.data,
                password=form.password.data,
            )
            db.session.add(user)
            db.session.commit()
            flash("Thank you for registering!")
            return redirect(url_for("users.login"))
        except IntegrityError:
            db.session.rollback()
            flash("Username or email already exists. Please choose a different one.")
            return redirect(url_for("users.register"))
    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    """Login User"""
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            abort(403, description=None)
        if user.check_password(form.password.data):
            login_user(user)
            flash("Logged in successfully!")

            # If user visits a page, they will be prompted to login
            next = request.args.get("next")

            if next == None or not next[0] == "/":
                next = url_for("core.index")

            return redirect(next)

    return render_template("login.html", form=form)


@users.route("/logout")
def logout():
    """Logout User"""
    logout_user()
    return redirect(url_for("core.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    """Show the account page of the user"""
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            picture = add_profile_pic(form.picture.data, username)
            current_user.profile_img = picture  # profile_img taken from models.user

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("User Account Updated!")
        return redirect(url_for("users.account"))

    elif request.method == "GET":
        # user is not submitting anything, so just grab the username and email
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_img = url_for("static", filename="profile_pics/" + current_user.profile_img)
    return render_template("account.html", profile_img=profile_img, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(
        username=username
    ).first_or_404()  # In case the user decides to manually input <username>, and then input it incorrectly, return a 404 error
    # Grab all blog posts by the particular user and sort the posts by date in decreasing order
    # paginate allows us to have pages. Here we have 5 blog posts per page
    blog_posts = (
        BlogPost.query.filter_by(author=user)
        .order_by(BlogPost.date.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_blog_posts.html", blog_posts=blog_posts, user=user)

website/templates/about.html
{# djlint:off H030, H031, T003 #}
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block content %}
  <div class="jumbotron">
    <h1>Info about this blog website</h1>
    <p>
      This is a blog website that allows users to view various blog posts. To add their own blog, the user must create their account. The account will be secured and hackers won't be able to hack into the website.
    </p>
  </div>
{% endblock %}

website/templates/account.html
{# djlint:off T003, H006 #}
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <div align="center">
      <h1>
        Welcome to the page, <b>{{ current_user.username|upper }}</b>!
      </h1>
      <img align="center"
           src="{{ url_for('static', filename='profile_pics/' + current_user.profile_img) }}"
           alt="username picture">
    </div>
  </div>
  <div class="container">
    <form method="post" action="" enctype="multipart/form-data">
      <div class="form-group"></div>
      {{ form.hidden_tag() }}
      <div class="form-group">{{ form.username.label(class='form-group') }}{{ form.username(class='form-control') }}</div>
      <div class="form-group">{{ form.email.label(class='form-group') }}{{ form.email(class='form-control') }}</div>
      <div class="form-group">
        {{ form.picture.label(class='form-group') }}{{ form.picture(class='form-control', accept='image/*') }}
      </div>
      <div class="form-group">{{ form.submit(class='btn btn-primary') }}</div>
    </form>
  </div>
{% endblock %}

website/templates/base.html
{# djlint:off H030, H031, T003 #}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      {% block title %}Blog Post Website{% endblock %}
    </title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
          crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>
    <script>
              $(document).ready(function () {
                  // Function to display flash messages as pop-up alerts
                  function displayFlashMessages() {
                      {% with messages = get_flashed_messages() %}
                          {% for message in messages %}
                              alert('{{ message }}');
                          {% endfor %}
                      {% endwith %}
                  }
                  // Call the function when the document is ready
                  displayFlashMessages();
              });
    </script>
  </head>
  <body>
    <ul class="nav">
      <li class="nav-link">
        <a href="{{ url_for("core.index") }}">Home</a>
      </li>
      <li class="nav-link">
        <a href="{{ url_for("core.info") }}">About</a>
      </li>
      {% if current_user.is_authenticated %}
        <li class="nav-link">
          <a href="{{ url_for("users.logout") }}">Logout</a>
        </li>
        <li class="nav-link">
          <a href="{{ url_for("users.account") }}">Account</a>
        </li>
        <li class="nav-link">
          <a href="{{ url_for("blog_posts.create_post") }}">Create Post</a>
        </li>
      {% else %}
        <li class="nav-link">
          <a href="{{ url_for("users.login") }}">Login</a>
        </li>
        <li class="nav-link">
          <a href="{{ url_for("users.register") }}">Register</a>
        </li>
      {% endif %}
    </ul>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

website/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <form class="form-group" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {{ form.title(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.text.label(class="form-control-label") }}
                {{ form.text(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">{{ form.submit(class="btn btn-outline-info") }}</div>
        </form>
    </div>
{% endblock content %}

website/templates/index.html
{# djlint:off H030, H031, T003 #}
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1 align="center">Blog Website</h1>
  </div>
  <div class="container">
    {% for post in blog_posts.items %}
      <div class="card">
        <div class="card-body">
          <h2>
            <a class="card-title"
               href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a>
          </h2>
          <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
          <p>Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
          <a class="btn btn-primary"
             href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">Read Blog Post</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <nav aria-label="Page Navigation Example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        <!-- Disable clicking on the current page, since you don't want to keep refreshing -->
        {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
          </li>
        {% else %}
          <li class="page-item ">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}

website/templates/login.html
{# djlint:off H029, T003 #}
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{ form.hidden_tag() }} <!-- protects against CSRF attacks-->
    {{ form.email.label }}{{ form.email }}
    <br>
    {{ form.password.label }}{{ form.password }}
    <br>
    {{ form.submit() }}
    <br>
  </form>
{% endblock %}
<!--
<div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
  <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
  <label for="floatingPassword">Password</label>
</div>
-->

website/templates/register.html
{# djlint:off H029, T003 #}
{% extends "base.html" %}
{% block content %}
  <form method="POST">
    {{ form.hidden_tag() }} <!-- protects against CSRF attacks-->
    {{ form.email.label }}{{ form.email }}
    <br>
    {{ form.username.label }}{{ form.username }}
    <br>
    {{ form.password.label }}{{ form.password }}
    <br>
    {{ form.confirm_password.label }}{{ form.confirm_password }}
    <br>
    {{ form.submit() }}
    <br>
  </form>
{% endblock %}
<!--
<div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
  <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
  <label for="floatingPassword">Password</label>
</div>
-->

website/templates/user_blog_posts.html
{# djlint:off T003, H006 #}
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>
                    Welcome to the page, <b>{{ user.username|upper }}</b>
                </h1>
                <img src="{{ url_for('static', filename='profile_pics/'+user.profile_img) }}"
                     alt="Profile Image">
            </div>
        </div>
        {% for post in blog_posts.items %}
            <div class="card">
                <div class="card-body">
                    <h2>
                        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a>
                    </h2>
                    Written By: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <p class="text-muted">Published on: {{ post.date.strftime("%Y-%m-%d") }}</p>
                    <br>
                    <p>{{ post.text }}</p>
                    <br>
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- Capabilities for page navigation -->
    <nav aria-label="Page Navigation Example">
        <ul class="pagination justify-content-center">
            {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                <!-- Disable clicking on the current page, since you don't want to keep refreshing -->
                {% if blog_posts.page == page_num %}
                    <li class="page-item disabled">
                        <a class="page-link"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item ">
                        <a class="page-link"
                           href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
{% endblock %}

website/templates/view_blog.html
{# djlint:off H023 #}
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>{{ title }}</h1>
        <h2>Written by: {{ post.author.username }}</h2>
        <h3>Published: {{ date.strftime("%B %d, %Y") }}</h3>
        <p>{{ post.text }}</p>
        {% if post.author == current_user %}
            <div>
                <a href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
                <button type="button"
                        class="btn btn-danger"
                        data-toggle="modal"
                        data-target="#del_modal"
                        name="button">Delete</button>
            </div>
        {% endif %}
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="del_modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete the post?</p>
                </div>
                <div class="modal-footer">
                    <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}"
                          method="post">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}